using System.Collections.Generic;

namespace PeakAchiever.Localization;

internal enum ModTextKey
{
    StatusAttainable,
    StatusHolding,
    StatusAchieved,
    ScopeLifetime,
    LimitRate,
    Eta,
    SecretPlaceholder,
    ReasonBiomeAbsent,
    ReasonBiomeLeft,
    ReasonTookFallDamage,
    ReasonAtePackagedFood,
    ReasonPassedOut,
    ReasonPlacedPermanentItem,
    ReasonRunTooLong,
    ReasonTooMuchHeat,
    ReasonTooMuchCold,
    ReasonTooManySpores,
    ReasonHitByTrap,
    ReasonRunLost,
    HintClickToPin,
    HintClickToUnpin,
    HintClickToPinForAlly,
    RefusalBoardFull,
    RefusalConflict,
    HintConflict,
    HintNotOnTodaysMap,
    HintNotOnThisMap,
    ChecklistNotOnMap,
    HintSuggestedToday,
    HintSuggestedThisMap,
    StatsButton,
    TeamButton,
    TeamTitle,
    TeamSummary,
    TeamGroupNobody,
    TeamGroupSome,
    TeamRecommended,
    TeamHaveIt,
    TeamMissingFor,
    TeamWithoutTheMod,
    RefusalTeamFull,
    ControlsToggleTracker,
    SettingsMaxPins,
    SettingsMaxTeamPins,
    ControlsKeySet,
    StatsTitle,
    StatsAscentFallback,
    StatsColumnBiome,
    StatsColumnTimes,
    StatsColumnMedian,
    StatsColumnBest,
    StatsLayoutTotal,
    StatsEmpty,
    StatsNoLowerAscent,
    StatsNoHigherAscent,
    StatsErase,
    StatsEraseConfirm,
    StatsErased,
    StatsEraseFailed,
    StatsClose,
    AchievementsDisabled,
    ChipAllRuns,
    ChipForAlly,
    StatusYouHaveIt,
    LimitLeft,
    BiomeNow,
    BiomeNext,
    BiomeLater,
    NeedsAll,
    NeedsOneOf,
    NeedsHelps,
    NeedsCount,
    LocatorBell,
    LocatorAntlion,
    LocatorTomb,
    LocatorDistance,
    SettingsMarkers,
    MarkerLabel,
    GroupTeam,
    GroupOwn,
}

/// <summary>
/// The mod's own strings. Badge names and descriptions come from the game's table instead.
/// Each row holds one string per <see cref="LocalizedText.Language"/>, in that enum's order, like the
/// game's own table (LocalizedText.GetText reads list[(int)CURRENT_LANGUAGE], v2.6.b).
/// </summary>
internal static class ModText
{
    // Typography and words follow the game's own table (Localized_Text.csv, v2.6.b): a no-break space
    // (U+00A0) before ':' in French, and before '%' in French, German and Spanish; '%' leads the number in
    // Turkish; Chinese and Japanese take a full-width '：', Simplified Chinese and Japanese full-width '（）'. Badge, scout, ascent, biome and expedition
    // are the game's terms in each language (its BADGELOCKED, DESC_CLUTCH, ASCENT 1, BIOME1 and DESC_FORAGING rows).
    internal static readonly Dictionary<ModTextKey, string[]> Table = new()
    {
        [ModTextKey.StatusAttainable] = Row(
            english: "Doable",
            french: "Faisable",
            italian: "Fattibile",
            german: "Machbar",
            spanishSpain: "Posible",
            spanishLatam: "Posible",
            brPortuguese: "Possível",
            russian: "Выполнимо",
            ukrainian: "Досяжно",
            simplifiedChinese: "可达成",
            traditionalChinese: "可達成",
            japanese: "達成可能",
            korean: "달성 가능",
            polish: "Wykonalne",
            turkish: "Yapılabilir"
        ),
        [ModTextKey.StatusHolding] = Row(
            english: "Holding so far",
            french: "Tenu jusqu'ici",
            italian: "Finora rispettato",
            german: "Bisher gehalten",
            spanishSpain: "Cumplido por ahora",
            spanishLatam: "Cumplido hasta ahora",
            brPortuguese: "Mantido até agora",
            russian: "Пока выполняется",
            ukrainian: "Поки виконується",
            simplifiedChinese: "目前保持中",
            traditionalChinese: "目前維持中",
            japanese: "今のところ維持",
            korean: "아직 유지 중",
            polish: "Na razie się trzyma",
            turkish: "Şimdilik sürüyor"
        ),
        [ModTextKey.StatusAchieved] = Row(
            english: "Earned",
            french: "Obtenu",
            italian: "Ottenuto",
            german: "Erhalten",
            spanishSpain: "Conseguida",
            spanishLatam: "Obtenida",
            brPortuguese: "Conquistada",
            russian: "Получен",
            ukrainian: "Отримано",
            simplifiedChinese: "已获得",
            traditionalChinese: "已獲得",
            japanese: "獲得済み",
            korean: "획득 완료",
            polish: "Zdobyta",
            turkish: "Kazanıldı"
        ),
        [ModTextKey.ChipAllRuns] = Row(
            english: "All runs",
            french: "Toutes les parties",
            italian: "Tutte le partite",
            german: "Alle Partien",
            spanishSpain: "Todas las partidas",
            spanishLatam: "Todas las partidas",
            brPortuguese: "Todas as partidas",
            russian: "Все экспедиции",
            ukrainian: "Усі експедиції",
            simplifiedChinese: "所有探险",
            traditionalChinese: "所有探險",
            japanese: "全探検",
            korean: "모든 원정",
            polish: "Wszystkie wyprawy",
            turkish: "Tüm keşifler"
        ),
        [ModTextKey.ChipForAlly] = Row(
            english: "For an ally",
            french: "Pour un allié",
            italian: "Per un amico",
            german: "Für einen Freund",
            spanishSpain: "Para un amigo",
            spanishLatam: "Para un amigo",
            brPortuguese: "Para um amigo",
            russian: "Для друга",
            ukrainian: "Для друга",
            simplifiedChinese: "为好友",
            traditionalChinese: "為好友",
            japanese: "フレンド用",
            korean: "친구용",
            polish: "Dla znajomego",
            turkish: "Arkadaş için"
        ),
        [ModTextKey.StatusYouHaveIt] = Row(
            english: "You have it",
            french: "Vous l'avez",
            italian: "Ce l'hai già",
            german: "Hast du schon",
            spanishSpain: "Ya la tienes",
            spanishLatam: "Ya la tienes",
            brPortuguese: "Você já tem",
            russian: "У вас уже есть",
            ukrainian: "У вас уже є",
            simplifiedChinese: "你已拥有",
            traditionalChinese: "你已擁有",
            japanese: "自分は獲得済み",
            korean: "이미 보유",
            polish: "Masz ją już",
            turkish: "Sende var"
        ),
        [ModTextKey.LimitLeft] = Row(
            english: "{0}% left",
            french: "Reste {0}\u00A0%",
            italian: "Restano {0}%",
            german: "Noch {0}\u00A0%",
            spanishSpain: "Quedan {0}\u00A0%",
            spanishLatam: "Quedan {0}\u00A0%",
            brPortuguese: "Restam {0}%",
            russian: "Осталось {0}%",
            ukrainian: "Залишилося {0}%",
            simplifiedChinese: "剩余 {0}%",
            traditionalChinese: "剩餘 {0}%",
            japanese: "残り{0}%",
            korean: "{0}% 남음",
            polish: "Zostało {0}%",
            turkish: "%{0} kaldı"
        ),
        [ModTextKey.BiomeNow] = Row(
            english: "Now, in the {0}",
            french: "Maintenant\u00A0: {0}",
            italian: "Ora: {0}",
            german: "Jetzt: {0}",
            spanishSpain: "Ahora: {0}",
            spanishLatam: "Ahora: {0}",
            brPortuguese: "Agora: {0}",
            russian: "Сейчас: {0}",
            ukrainian: "Зараз: {0}",
            simplifiedChinese: "当前：{0}",
            traditionalChinese: "目前：{0}",
            japanese: "現在：{0}",
            korean: "현재: {0}",
            polish: "Teraz: {0}",
            turkish: "Şu an: {0}"
        ),
        [ModTextKey.BiomeNext] = Row(
            english: "{0}, next biome",
            french: "{0}, prochain biome",
            italian: "{0}, prossimo bioma",
            german: "{0}, nächstes Biom",
            spanishSpain: "{0}, próximo bioma",
            spanishLatam: "{0}, próximo bioma",
            brPortuguese: "{0}, próximo bioma",
            russian: "{0}, следующий биом",
            ukrainian: "{0}, наступний біом",
            simplifiedChinese: "{0}，下一个地形",
            traditionalChinese: "{0}，下一個生態系",
            japanese: "{0}、次のバイオーム",
            korean: "{0}, 다음 구역",
            polish: "{0}, następny biom",
            turkish: "{0}, sonraki biyom"
        ),
        [ModTextKey.BiomeLater] = Row(
            english: "{0}, in {1} biomes",
            french: "{0}, dans {1} biomes",
            italian: "{0}, tra {1} biomi",
            german: "{0}, in {1} Biomen",
            spanishSpain: "{0}, en {1} biomas",
            spanishLatam: "{0}, en {1} biomas",
            brPortuguese: "{0}, em {1} biomas",
            russian: "{0}, биомов впереди: {1}",
            ukrainian: "{0}, біомів попереду: {1}",
            simplifiedChinese: "{0}，{1} 个地形后",
            traditionalChinese: "{0}，{1} 個生態系後",
            japanese: "{0}、{1}つ先のバイオーム",
            korean: "{0}, {1}구역 뒤",
            polish: "{0}, biomów przed tobą: {1}",
            turkish: "{0}, {1} biyom sonra"
        ),
        [ModTextKey.NeedsAll] = Row(
            english: "Needs",
            french: "Requis",
            italian: "Serve",
            german: "Benötigt",
            spanishSpain: "Requiere",
            spanishLatam: "Requiere",
            brPortuguese: "Requer",
            russian: "Нужно",
            ukrainian: "Потрібно",
            simplifiedChinese: "需要",
            traditionalChinese: "需要",
            japanese: "必要",
            korean: "필요",
            polish: "Wymaga",
            turkish: "Gerekli"
        ),
        [ModTextKey.NeedsOneOf] = Row(
            english: "One of",
            french: "Parmi",
            italian: "Uno tra",
            german: "Eins davon",
            spanishSpain: "Uno de",
            spanishLatam: "Uno de",
            brPortuguese: "Um destes",
            russian: "Одно из",
            ukrainian: "Одне з",
            simplifiedChinese: "任选其一",
            traditionalChinese: "任選其一",
            japanese: "いずれか",
            korean: "다음 중 하나",
            polish: "Jedno z",
            turkish: "Şunlardan biri"
        ),
        [ModTextKey.NeedsHelps] = Row(
            english: "Helps",
            french: "Utile",
            italian: "Utile",
            german: "Hilft",
            spanishSpain: "Ayuda",
            spanishLatam: "Ayuda",
            brPortuguese: "Ajuda",
            russian: "Помогает",
            ukrainian: "Допомагає",
            simplifiedChinese: "有帮助",
            traditionalChinese: "有幫助",
            japanese: "役立つ",
            korean: "도움",
            polish: "Pomaga",
            turkish: "Yardımcı"
        ),
        [ModTextKey.NeedsCount] = Row(
            english: "×{0}",
            french: "×{0}",
            italian: "×{0}",
            german: "×{0}",
            spanishSpain: "×{0}",
            spanishLatam: "×{0}",
            brPortuguese: "×{0}",
            russian: "×{0}",
            ukrainian: "×{0}",
            simplifiedChinese: "×{0}",
            traditionalChinese: "×{0}",
            japanese: "×{0}",
            korean: "×{0}",
            polish: "×{0}",
            turkish: "×{0}"
        ),
        [ModTextKey.LocatorBell] = Row(
            english: "Unlit belltower",
            french: "Clocher éteint",
            italian: "Torre campanaria spenta",
            german: "Dunkler Glockenturm",
            spanishSpain: "Campanario apagado",
            spanishLatam: "Campanario apagado",
            brPortuguese: "Torre de sino apagada",
            russian: "Тёмная колокольня",
            ukrainian: "Темна дзвіниця",
            simplifiedChinese: "未点亮的钟塔",
            traditionalChinese: "未點亮的鐘塔",
            japanese: "未点灯の鐘楼",
            korean: "꺼진 종탑",
            polish: "Nieoświetlona dzwonnica",
            turkish: "Sönük çan kulesi"
        ),
        [ModTextKey.LocatorAntlion] = Row(
            english: "Antlion",
            french: "Fourmilion",
            italian: "Formicaleone",
            german: "Ameisenlöwe",
            spanishSpain: "Hormiga león",
            spanishLatam: "Hormiga león",
            brPortuguese: "Formiga-leão",
            russian: "Муравьиный лев",
            ukrainian: "Мурашиний лев",
            simplifiedChinese: "蚁狮",
            traditionalChinese: "蟻蛉",
            japanese: "アリジゴク",
            korean: "개미귀신",
            polish: "Mrówkolew",
            turkish: "Karıncaaslanı"
        ),
        [ModTextKey.LocatorTomb] = Row(
            english: "Mesa tomb",
            french: "Tombe du Plateau",
            italian: "Tomba della Mesa",
            german: "Gruft der Mesa",
            spanishSpain: "Tumba de la Meseta",
            spanishLatam: "Tumba de la Mesa",
            brPortuguese: "Tumba da Chapada",
            russian: "Гробница Столовой горы",
            ukrainian: "Гробниця Меси",
            simplifiedChinese: "方山古墓",
            traditionalChinese: "平頂山墓穴",
            japanese: "メサの墓地",
            korean: "메사 무덤",
            polish: "Grobowiec na Stoliwie",
            turkish: "Çorak Yamaç mezarı"
        ),
        [ModTextKey.LocatorDistance] = Row(
            english: "{0} m",
            french: "{0}\u00A0m",
            italian: "{0} m",
            german: "{0} m",
            spanishSpain: "{0} m",
            spanishLatam: "{0} m",
            brPortuguese: "{0} m",
            russian: "{0} m",
            ukrainian: "{0} m",
            simplifiedChinese: "{0} m",
            traditionalChinese: "{0} m",
            japanese: "{0} m",
            korean: "{0} m",
            polish: "{0} m",
            turkish: "{0} m"
        ),
        [ModTextKey.GroupTeam] = Row(
            english: "TEAM · SET BY THE HOST",
            french: "ÉQUIPE · CHOISIES PAR L'HÔTE",
            italian: "SQUADRA · SCELTI DALL'HOST",
            german: "TEAM · VOM HOST GEWÄHLT",
            spanishSpain: "EQUIPO · ELEGIDAS POR EL ANFITRIÓN",
            spanishLatam: "EQUIPO · ELEGIDAS POR EL ANFITRIÓN",
            brPortuguese: "EQUIPE · ESCOLHIDAS PELO ANFITRIÃO",
            russian: "КОМАНДА · ВЫБОР ХОСТА",
            ukrainian: "КОМАНДА · ВИБІР ХОСТА",
            simplifiedChinese: "队伍 · 由房主设置",
            traditionalChinese: "隊伍 · 由主持人設定",
            japanese: "チーム · ホストが設定",
            korean: "팀 · 호스트가 지정",
            polish: "DRUŻYNA · WYBÓR HOSTA",
            turkish: "TAKIM · KURUCUNUN SEÇİMİ"
        ),
        [ModTextKey.GroupOwn] = Row(
            english: "YOUR PINS",
            french: "VOS ÉPINGLES",
            italian: "I TUOI FISSATI",
            german: "VON DIR ANGEHEFTET",
            spanishSpain: "TUS FIJADAS",
            spanishLatam: "TUS FIJADAS",
            brPortuguese: "SUAS FIXADAS",
            russian: "ВАШИ ЗАКРЕПЛЁННЫЕ",
            ukrainian: "ВАШІ ЗАКРІПЛЕНІ",
            simplifiedChinese: "你的固定",
            traditionalChinese: "你的釘選",
            japanese: "自分のピン留め",
            korean: "내 고정",
            polish: "TWOJE PRZYPIĘTE",
            turkish: "SENİN SABİTLEDİKLERİN"
        ),
        [ModTextKey.MarkerLabel] = Row(
            english: "{0} · {1} m",
            french: "{0} · {1}\u00A0m",
            italian: "{0} · {1} m",
            german: "{0} · {1} m",
            spanishSpain: "{0} · {1} m",
            spanishLatam: "{0} · {1} m",
            brPortuguese: "{0} · {1} m",
            russian: "{0} · {1} m",
            ukrainian: "{0} · {1} m",
            simplifiedChinese: "{0} · {1} m",
            traditionalChinese: "{0} · {1} m",
            japanese: "{0} · {1} m",
            korean: "{0} · {1} m",
            polish: "{0} · {1} m",
            turkish: "{0} · {1} m"
        ),
        [ModTextKey.SettingsMarkers] = Row(
            english: "PEAKACHIEVER: ON-SCREEN MARKERS",
            french: "PEAKACHIEVER\u00A0: REPÈRES À L'ÉCRAN",
            italian: "PEAKACHIEVER: INDICATORI A SCHERMO",
            german: "PEAKACHIEVER: BILDSCHIRMMARKIERUNGEN",
            spanishSpain: "PEAKACHIEVER: MARCADORES EN PANTALLA",
            spanishLatam: "PEAKACHIEVER: MARCADORES EN PANTALLA",
            brPortuguese: "PEAKACHIEVER: MARCADORES NA TELA",
            russian: "PEAKACHIEVER: МЕТКИ НА ЭКРАНЕ",
            ukrainian: "PEAKACHIEVER: МІТКИ НА ЕКРАНІ",
            simplifiedChinese: "PEAKACHIEVER：屏幕标记",
            traditionalChinese: "PEAKACHIEVER：螢幕標記",
            japanese: "PEAKACHIEVER：画面上のマーカー",
            korean: "PEAKACHIEVER: 화면 표시",
            polish: "PEAKACHIEVER: ZNACZNIKI NA EKRANIE",
            turkish: "PEAKACHIEVER: EKRAN İŞARETÇİLERİ"
        ),
        [ModTextKey.ScopeLifetime] = Row(
            english: "LIFETIME",
            french: "À VIE",
            italian: "COMPLESSIVO",
            german: "GESAMT",
            spanishSpain: "ACUMULADO",
            spanishLatam: "ACUMULADO",
            brPortuguese: "ACUMULADO",
            russian: "ЗА ВСЁ ВРЕМЯ",
            ukrainian: "ЗА ВЕСЬ ЧАС",
            simplifiedChinese: "累计",
            traditionalChinese: "累計",
            japanese: "累計",
            korean: "누적",
            polish: "ŁĄCZNIE",
            turkish: "TOPLAM"
        ),
        [ModTextKey.Eta] = Row(
            english: "ETA {0}",
            french: "Arrivée estimée\u00A0: {0}",
            italian: "Arrivo stimato: {0}",
            german: "Ankunft ca. {0}",
            spanishSpain: "Llegada estimada: {0}",
            spanishLatam: "Llegada estimada: {0}",
            brPortuguese: "Chegada prevista: {0}",
            russian: "Прибытие: \u00A0{0}",
            ukrainian: "Прибуття: \u00A0{0}",
            simplifiedChinese: "预计到达：{0}",
            traditionalChinese: "預計抵達：{0}",
            japanese: "到着予定：{0}",
            korean: "예상 도착: {0}",
            polish: "Szac. przybycie: {0}",
            turkish: "Tahmini varış: {0}"
        ),
        [ModTextKey.LimitRate] = Row(
            english: "max {0}% / {1}%",
            french: "max {0}\u00A0% / {1}\u00A0%",
            italian: "max {0}% / {1}%",
            german: "max. {0}\u00A0% / {1}\u00A0%",
            spanishSpain: "máx. {0}\u00A0% / {1}\u00A0%",
            spanishLatam: "máx. {0}\u00A0% / {1}\u00A0%",
            brPortuguese: "máx. {0}% / {1}%",
            russian: "макс. {0}% / {1}%",
            ukrainian: "макс. {0}% / {1}%",
            simplifiedChinese: "最多 {0}% / {1}%",
            traditionalChinese: "最多 {0}% / {1}%",
            japanese: "最大 {0}% / {1}%",
            korean: "최대 {0}% / {1}%",
            polish: "maks. {0}% / {1}%",
            turkish: "en fazla %{0} / %{1}"
        ),
        [ModTextKey.SecretPlaceholder] = Row(
            english: "???",
            french: "???",
            italian: "???",
            german: "???",
            spanishSpain: "???",
            spanishLatam: "???",
            brPortuguese: "???",
            russian: "???",
            ukrainian: "???",
            simplifiedChinese: "???",
            traditionalChinese: "???",
            japanese: "???",
            korean: "???",
            polish: "???",
            turkish: "???"
        ),
        [ModTextKey.ReasonBiomeAbsent] = Row(
            english: "Impossible: no {0} this run",
            french: "Impossible\u00A0: pas de {0} dans cette run",
            italian: "Impossibile: {0} assente in questa spedizione",
            german: "Unmöglich: {0} fehlt in dieser Expedition",
            spanishSpain: "Imposible: no hay {0} en esta expedición",
            spanishLatam: "Imposible: no hay {0} en esta expedición",
            brPortuguese: "Impossível: sem {0} nesta expedição",
            russian: "Невозможно: биома {0} нет в экспедиции",
            ukrainian: "Неможливо: біому {0} немає в експедиції",
            simplifiedChinese: "无法达成：本次探险没有{0}",
            traditionalChinese: "無法達成：本次探險沒有{0}",
            japanese: "達成不可：今回の探検に{0}はない",
            korean: "달성 불가: 이번 원정에 {0} 없음",
            polish: "Niemożliwe: brak biomu {0} w tej wyprawie",
            turkish: "İmkansız: bu keşif gezisinde {0} yok"
        ),
        [ModTextKey.ReasonBiomeLeft] = Row(
            english: "Impossible: {0} left behind",
            french: "Impossible\u00A0: {0} déjà quitté",
            italian: "Impossibile: {0} ormai superato",
            german: "Unmöglich: {0} schon verlassen",
            spanishSpain: "Imposible: ya has dejado atrás {0}",
            spanishLatam: "Imposible: ya dejaste atrás {0}",
            brPortuguese: "Impossível: {0} já ficou para trás",
            russian: "Невозможно: биом {0} уже пройден",
            ukrainian: "Неможливо: біом {0} вже пройдено",
            simplifiedChinese: "无法达成：已离开{0}",
            traditionalChinese: "無法達成：已離開{0}",
            japanese: "達成不可：{0}を通過済み",
            korean: "달성 불가: {0} 구역 이미 통과",
            polish: "Niemożliwe: biom {0} już za tobą",
            turkish: "İmkansız: {0} geride kaldı"
        ),
        [ModTextKey.ReasonTookFallDamage] = Row(
            english: "Impossible: fall damage taken",
            french: "Impossible\u00A0: dégâts de chute subis",
            italian: "Impossibile: danni da caduta subiti",
            german: "Unmöglich: Fallschaden erlitten",
            spanishSpain: "Imposible: has sufrido daño por caída",
            spanishLatam: "Imposible: recibiste daño por caída",
            brPortuguese: "Impossível: dano por queda recebido",
            russian: "Невозможно: получен урон от падения",
            ukrainian: "Неможливо: отримано шкоду від падіння",
            simplifiedChinese: "无法达成：受到掉落伤害",
            traditionalChinese: "無法達成：受到墜落傷害",
            japanese: "達成不可：落下ダメージを受けた",
            korean: "달성 불가: 추락 피해를 받음",
            polish: "Niemożliwe: otrzymano obrażenia od upadku",
            turkish: "İmkansız: düşme hasarı alındı"
        ),
        [ModTextKey.ReasonAtePackagedFood] = Row(
            english: "Impossible: packaged food eaten",
            french: "Impossible\u00A0: nourriture emballée mangée",
            italian: "Impossibile: cibo confezionato mangiato",
            german: "Unmöglich: abgepackte Nahrung gegessen",
            spanishSpain: "Imposible: has comido alimentos envasados",
            spanishLatam: "Imposible: comiste alimentos empaquetados",
            brPortuguese: "Impossível: alimento embalado consumido",
            russian: "Невозможно: съедена фасованная пища",
            ukrainian: "Неможливо: з’їдено пайок",
            simplifiedChinese: "无法达成：食用了包装食品",
            traditionalChinese: "無法達成：吃了包裝食品",
            japanese: "達成不可：パッケージ食品を食べた",
            korean: "달성 불가: 포장된 음식을 먹음",
            polish: "Niemożliwe: zjedzono pakowane jedzenie",
            turkish: "İmkansız: paketli gıda yendi"
        ),
        [ModTextKey.ReasonPassedOut] = Row(
            english: "Impossible: you passed out",
            french: "Impossible\u00A0: vous vous êtes évanoui",
            italian: "Impossibile: hai perso i sensi",
            german: "Unmöglich: du warst bewusstlos",
            spanishSpain: "Imposible: has perdido el conocimiento",
            spanishLatam: "Imposible: perdiste el conocimiento",
            brPortuguese: "Impossível: você desmaiou",
            russian: "Невозможно: вы потеряли сознание",
            ukrainian: "Неможливо: ви знепритомніли",
            simplifiedChinese: "无法达成：你昏迷了",
            traditionalChinese: "無法達成：你失去了意識",
            japanese: "達成不可：意識を失った",
            korean: "달성 불가: 의식을 잃음",
            polish: "Niemożliwe: utrata przytomności",
            turkish: "İmkansız: bayıldın"
        ),
        [ModTextKey.ReasonPlacedPermanentItem] = Row(
            english: "Impossible: permanent item placed",
            french: "Impossible\u00A0: objet permanent posé",
            italian: "Impossibile: oggetto permanente posizionato",
            german: "Unmöglich: dauerhaften Gegenstand platziert",
            spanishSpain: "Imposible: has colocado un objeto permanente",
            spanishLatam: "Imposible: colocaste un objeto permanente",
            brPortuguese: "Impossível: item permanente colocado",
            russian: "Невозможно: размещён постоянный предмет",
            ukrainian: "Неможливо: розміщено постійний предмет",
            simplifiedChinese: "无法达成：放置了永久物品",
            traditionalChinese: "無法達成：放置了永久物品",
            japanese: "達成不可：永続アイテムを設置した",
            korean: "달성 불가: 영구 아이템을 설치함",
            polish: "Niemożliwe: umieszczono trwały przedmiot",
            turkish: "İmkansız: kalıcı bir eşya yerleştirildi"
        ),
        [ModTextKey.ReasonRunTooLong] = Row(
            english: "Impossible: over one hour",
            french: "Impossible\u00A0: plus d'une heure écoulée",
            italian: "Impossibile: più di un'ora",
            german: "Unmöglich: über eine Stunde",
            spanishSpain: "Imposible: más de una hora",
            spanishLatam: "Imposible: más de una hora",
            brPortuguese: "Impossível: mais de uma hora",
            russian: "Невозможно: прошло больше часа",
            ukrainian: "Неможливо: минуло понад годину",
            simplifiedChinese: "无法达成：已超过一小时",
            traditionalChinese: "無法達成：已超過一小時",
            japanese: "達成不可：1時間を超えた",
            korean: "달성 불가: 한 시간 초과",
            polish: "Niemożliwe: minęła ponad godzina",
            turkish: "İmkansız: bir saati geçti"
        ),
        [ModTextKey.ReasonTooMuchHeat] = Row(
            english: "Impossible: too much heat taken",
            french: "Impossible\u00A0: trop de chaleur subie",
            italian: "Impossibile: troppo calore subito",
            german: "Unmöglich: zu viel Wärme",
            spanishSpain: "Imposible: demasiado calor",
            spanishLatam: "Imposible: demasiado calor",
            brPortuguese: "Impossível: calor demais",
            russian: "Невозможно: слишком сильный нагрев",
            ukrainian: "Неможливо: забагато тепла",
            simplifiedChinese: "无法达成：热量过高",
            traditionalChinese: "無法達成：炎熱過高",
            japanese: "達成不可：体温が上がりすぎた",
            korean: "달성 불가: 열이 너무 높음",
            polish: "Niemożliwe: za dużo ciepła",
            turkish: "İmkansız: ısı çok yükseldi"
        ),
        [ModTextKey.ReasonTooMuchCold] = Row(
            english: "Impossible: too much cold taken",
            french: "Impossible\u00A0: trop de froid subi",
            italian: "Impossibile: troppo freddo subito",
            german: "Unmöglich: zu viel Kälte",
            spanishSpain: "Imposible: demasiado frío",
            spanishLatam: "Imposible: demasiado frío",
            brPortuguese: "Impossível: frio demais",
            russian: "Невозможно: слишком сильный холод",
            ukrainian: "Неможливо: забагато холоду",
            simplifiedChinese: "无法达成：寒冷值过高",
            traditionalChinese: "無法達成：寒冷過高",
            japanese: "達成不可：凍傷が進みすぎた",
            korean: "달성 불가: 추위가 너무 높음",
            polish: "Niemożliwe: za dużo zimna",
            turkish: "İmkansız: soğukluk çok yükseldi"
        ),
        [ModTextKey.ReasonTooManySpores] = Row(
            english: "Impossible: too many spores taken",
            french: "Impossible\u00A0: trop de spores subies",
            italian: "Impossibile: troppe spore subite",
            german: "Unmöglich: zu viele Sporen",
            spanishSpain: "Imposible: demasiadas esporas",
            spanishLatam: "Imposible: demasiadas esporas",
            brPortuguese: "Impossível: esporos demais",
            russian: "Невозможно: слишком много спор",
            ukrainian: "Неможливо: забагато спор",
            simplifiedChinese: "无法达成：孢子值过高",
            traditionalChinese: "無法達成：孢子過多",
            japanese: "達成不可：胞子を浴びすぎた",
            korean: "달성 불가: 포자가 너무 많음",
            polish: "Niemożliwe: za dużo zarodników",
            turkish: "İmkansız: spor çok yükseldi"
        ),
        [ModTextKey.ReasonRunLost] = Row(
            english: "Impossible: run lost",
            french: "Impossible\u00A0: run perdue",
            italian: "Impossibile: spedizione fallita",
            german: "Unmöglich: Expedition gescheitert",
            spanishSpain: "Imposible: expedición fallida",
            spanishLatam: "Imposible: expedición fallida",
            brPortuguese: "Impossível: expedição fracassada",
            russian: "Невозможно: экспедиция провалена",
            ukrainian: "Неможливо: експедицію провалено",
            simplifiedChinese: "无法达成：探险失败",
            traditionalChinese: "無法達成：探險失敗",
            japanese: "達成不可：探検に失敗した",
            korean: "달성 불가: 원정 실패",
            polish: "Niemożliwe: wyprawa przegrana",
            turkish: "İmkansız: keşif gezisi başarısız"
        ),
        [ModTextKey.ReasonHitByTrap] = Row(
            english: "Impossible: hit by a trap",
            french: "Impossible\u00A0: touché par un piège",
            italian: "Impossibile: colpito da una trappola",
            german: "Unmöglich: von einer Falle getroffen",
            spanishSpain: "Imposible: te ha alcanzado una trampa",
            spanishLatam: "Imposible: caíste en una trampa",
            brPortuguese: "Impossível: atingido por uma armadilha",
            russian: "Невозможно: вы попали в ловушку",
            ukrainian: "Неможливо: ви потрапили в пастку",
            simplifiedChinese: "无法达成：受到陷阱伤害",
            traditionalChinese: "無法達成：被陷阱擊中",
            japanese: "達成不可：罠にかかった",
            korean: "달성 불가: 함정에 맞음",
            polish: "Niemożliwe: trafiła cię pułapka",
            turkish: "İmkansız: tuzaktan darbe alındı"
        ),
        [ModTextKey.HintClickToPin] = Row(
            english: "Click: pin to tracker",
            french: "Clic\u00A0: épingler au traqueur",
            italian: "Clic: fissa nel tracker",
            german: "Klick: an den Tracker anheften",
            spanishSpain: "Clic: fijar en el rastreador",
            spanishLatam: "Clic: fijar en el rastreador",
            brPortuguese: "Clique: fixar no rastreador",
            russian: "Щелчок: закрепить в трекере",
            ukrainian: "Клік: закріпити в трекері",
            simplifiedChinese: "点击：固定到追踪器",
            traditionalChinese: "點擊：釘選到追蹤器",
            japanese: "クリック：トラッカーにピン留め",
            korean: "클릭: 추적기에 고정",
            polish: "Kliknij: przypnij do trackera",
            turkish: "Tıkla: takip paneline sabitle"
        ),
        [ModTextKey.HintClickToPinForAlly] = Row(
            english: "Click: pin to help an ally earn it",
            french: "Clic\u00A0: épingler pour aider un allié",
            italian: "Clic: fissa per aiutare un amico",
            german: "Klick: anheften, um einem Freund zu helfen",
            spanishSpain: "Clic: fijar para ayudar a un amigo",
            spanishLatam: "Clic: fijar para ayudar a un amigo",
            brPortuguese: "Clique: fixar para ajudar um amigo",
            russian: "Щелчок: закрепить, чтобы помочь другу",
            ukrainian: "Клік: закріпити, щоб допомогти другу",
            simplifiedChinese: "点击：固定以帮助好友获得",
            traditionalChinese: "點擊：釘選以協助好友取得",
            japanese: "クリック：ピン留めしてフレンドを手伝う",
            korean: "클릭: 고정해서 친구의 획득 돕기",
            polish: "Kliknij: przypnij, by pomóc znajomemu",
            turkish: "Tıkla: arkadaşına yardım için sabitle"
        ),
        [ModTextKey.HintClickToUnpin] = Row(
            english: "Click: unpin from tracker",
            french: "Clic\u00A0: retirer du traqueur",
            italian: "Clic: rimuovi dal tracker",
            german: "Klick: vom Tracker lösen",
            spanishSpain: "Clic: quitar del rastreador",
            spanishLatam: "Clic: quitar del rastreador",
            brPortuguese: "Clique: remover do rastreador",
            russian: "Щелчок: убрать из трекера",
            ukrainian: "Клік: прибрати з трекера",
            simplifiedChinese: "点击：从追踪器取消固定",
            traditionalChinese: "點擊：從追蹤器取消釘選",
            japanese: "クリック：トラッカーから外す",
            korean: "클릭: 추적기에서 고정 해제",
            polish: "Kliknij: odepnij od trackera",
            turkish: "Tıkla: takip panelinden kaldır"
        ),
        [ModTextKey.RefusalBoardFull] = Row(
            english: "{0} badges pinned at most. Unpin one, or raise the limit in Settings, General.",
            french: "{0} distinctions épinglées au maximum. Retirez-en une, ou augmentez la limite dans Paramètres, Général.",
            italian: "Al massimo {0} distintivi fissati. Rimuovine uno o alza il limite in Impostazioni, Generali.",
            german: "Höchstens {0} angeheftete Abzeichen. Löse eines oder erhöhe das Limit unter Einstellungen, Allgemein.",
            spanishSpain: "Máximo de {0} insignias fijadas. Quita una o sube el límite en Ajustes, General.",
            spanishLatam: "Máximo de {0} insignias fijadas. Quita una o aumenta el límite en Ajustes, General.",
            brPortuguese: "No máximo {0} insígnias fixadas. Remova uma ou aumente o limite em Configurações, Geral.",
            russian: "Можно закрепить не больше {0} значков. Уберите один или увеличьте лимит в разделе Настройки, Общие.",
            ukrainian: "Можна закріпити не більше {0} значків. Приберіть один або збільште ліміт у розділі Налаштування, Загальні параметри.",
            simplifiedChinese: "最多固定 {0} 枚奖章。请取消固定一枚，或在“设置”的“通用”中提高上限。",
            traditionalChinese: "最多釘選 {0} 枚徽章。請取消釘選一枚，或在「設定」的「一般」中提高上限。",
            japanese: "ピン留めできるバッジは最大{0}個です。1つ外すか、「設定」の「全般」で上限を上げてください。",
            korean: "배지는 최대 {0}개까지 고정할 수 있습니다. 하나를 해제하거나 설정의 일반에서 한도를 높이세요.",
            polish: "Limit przypiętych odznak: {0}. Odepnij jedną lub zwiększ limit w: Ustawienia, Ogólne.",
            turkish: "En fazla {0} rozet sabitlenebilir. Birini kaldır ya da Ayarlar, Genel bölümünden sınırı artır."
        ),
        [ModTextKey.RefusalConflict] = Row(
            english: "Can't be earned in the same run as {0}: no map has both their biomes. Unpin it first.",
            french: "Impossible dans la même run que {0}\u00A0: aucune carte n'a leurs deux biomes. Retirez-la d'abord.",
            italian: "Non ottenibile nella stessa spedizione di {0}: nessuna mappa ha entrambi i biomi. Rimuovilo prima.",
            german: "Nicht in derselben Expedition wie {0} machbar: Keine Karte hat beide Biome. Löse es zuerst.",
            spanishSpain: "No se puede conseguir en la misma expedición que {0}: ningún mapa tiene ambos biomas. Quítala primero.",
            spanishLatam: "No se puede obtener en la misma expedición que {0}: ningún mapa tiene ambos biomas. Quítala primero.",
            brPortuguese: "Não dá para obter na mesma expedição que {0}: nenhum mapa tem os dois biomas. Remova-a primeiro.",
            russian: "Не получить в одной экспедиции с этим значком: {0}. Ни на одной карте нет обоих биомов. Сначала уберите его.",
            ukrainian: "Не здобути в одній експедиції з цим значком: {0}. Жодна мапа не має обох біомів. Спершу приберіть його.",
            simplifiedChinese: "无法与{0}在同一次探险中获得：没有地图同时包含两者的地形。请先取消固定它。",
            traditionalChinese: "無法與{0}在同一次探險中取得：沒有地圖同時具有兩者的生態系。請先取消釘選它。",
            japanese: "{0}と同じ探検では獲得できません：両方のバイオームを含むマップがありません。先にそちらを外してください。",
            korean: "{0}와(과) 같은 원정에서 획득할 수 없습니다. 두 구역이 모두 있는 맵이 없습니다. 먼저 고정을 해제하세요.",
            polish: "Nie do zdobycia w jednej wyprawie z tą odznaką: {0}. Żadna mapa nie ma obu biomów. Najpierw ją odepnij.",
            turkish: "{0} ile aynı keşif gezisinde kazanılamaz: hiçbir haritada iki biyom birden yok. Önce onu kaldır."
        ),
        [ModTextKey.HintConflict] = Row(
            english: "Conflicts with {0}: no map has both their biomes",
            french: "Incompatible avec {0}\u00A0: aucune carte n'a leurs deux biomes",
            italian: "In conflitto con {0}: nessuna mappa ha entrambi i biomi",
            german: "Unvereinbar mit {0}: Keine Karte hat beide Biome",
            spanishSpain: "Incompatible con {0}: ningún mapa tiene ambos biomas",
            spanishLatam: "Incompatible con {0}: ningún mapa tiene ambos biomas",
            brPortuguese: "Incompatível com {0}: nenhum mapa tem os dois biomas",
            russian: "Несовместимо: {0}. Ни на одной карте нет обоих биомов",
            ukrainian: "Несумісно: {0}. Жодна мапа не має обох біомів",
            simplifiedChinese: "与{0}冲突：没有地图同时包含两者的地形",
            traditionalChinese: "與{0}衝突：沒有地圖同時具有兩者的生態系",
            japanese: "{0}と競合：両方のバイオームを含むマップがない",
            korean: "{0}와(과) 충돌: 두 구역이 모두 있는 맵이 없음",
            polish: "Konflikt: {0}. Żadna mapa nie ma obu biomów",
            turkish: "{0} ile çakışıyor: hiçbir haritada iki biyom birden yok"
        ),
        [ModTextKey.HintNotOnTodaysMap] = Row(
            english: "Not on today's map ({0})",
            french: "Pas sur la carte du jour ({0})",
            italian: "Non sulla mappa di oggi ({0})",
            german: "Nicht auf der heutigen Karte ({0})",
            spanishSpain: "No está en el mapa de hoy ({0})",
            spanishLatam: "No está en el mapa de hoy ({0})",
            brPortuguese: "Fora do mapa de hoje ({0})",
            russian: "Нет на сегодняшней карте ({0})",
            ukrainian: "Немає на сьогоднішній мапі ({0})",
            simplifiedChinese: "不在今天的地图上（{0}）",
            traditionalChinese: "不在今天的地圖上 ({0})",
            japanese: "今日のマップにない（{0}）",
            korean: "오늘의 맵에 없음 ({0})",
            polish: "Nie ma na dzisiejszej mapie ({0})",
            turkish: "Bugünün haritasında yok ({0})"
        ),
        [ModTextKey.HintNotOnThisMap] = Row(
            english: "Not on this map ({0})",
            french: "Pas sur cette carte ({0})",
            italian: "Non su questa mappa ({0})",
            german: "Nicht auf dieser Karte ({0})",
            spanishSpain: "No está en este mapa ({0})",
            spanishLatam: "No está en este mapa ({0})",
            brPortuguese: "Fora deste mapa ({0})",
            russian: "Нет на этой карте ({0})",
            ukrainian: "Немає на цій мапі ({0})",
            simplifiedChinese: "不在此地图上（{0}）",
            traditionalChinese: "不在此地圖上 ({0})",
            japanese: "このマップにない（{0}）",
            korean: "이 맵에 없음 ({0})",
            polish: "Nie ma na tej mapie ({0})",
            turkish: "Bu haritada yok ({0})"
        ),
        [ModTextKey.HintSuggestedToday] = Row(
            english: "Suggested: doable on today's map",
            french: "Suggéré\u00A0: faisable sur la carte du jour",
            italian: "Consigliato: fattibile sulla mappa di oggi",
            german: "Empfohlen: auf der heutigen Karte machbar",
            spanishSpain: "Sugerida: posible en el mapa de hoy",
            spanishLatam: "Sugerida: posible en el mapa de hoy",
            brPortuguese: "Sugerida: possível no mapa de hoje",
            russian: "Рекомендуем: выполнимо на сегодняшней карте",
            ukrainian: "Рекомендовано: досяжно на сьогоднішній мапі",
            simplifiedChinese: "推荐：今天的地图上可达成",
            traditionalChinese: "推薦：今天的地圖上可達成",
            japanese: "おすすめ：今日のマップで達成可能",
            korean: "추천: 오늘의 맵에서 달성 가능",
            polish: "Polecane: wykonalne na dzisiejszej mapie",
            turkish: "Önerilen: bugünün haritasında yapılabilir"
        ),
        [ModTextKey.HintSuggestedThisMap] = Row(
            english: "Suggested: doable on this map",
            french: "Suggéré\u00A0: faisable sur cette carte",
            italian: "Consigliato: fattibile su questa mappa",
            german: "Empfohlen: auf dieser Karte machbar",
            spanishSpain: "Sugerida: posible en este mapa",
            spanishLatam: "Sugerida: posible en este mapa",
            brPortuguese: "Sugerida: possível neste mapa",
            russian: "Рекомендуем: выполнимо на этой карте",
            ukrainian: "Рекомендовано: досяжно на цій мапі",
            simplifiedChinese: "推荐：此地图上可达成",
            traditionalChinese: "推薦：此地圖上可達成",
            japanese: "おすすめ：このマップで達成可能",
            korean: "추천: 이 맵에서 달성 가능",
            polish: "Polecane: wykonalne na tej mapie",
            turkish: "Önerilen: bu haritada yapılabilir"
        ),
        [ModTextKey.ChecklistNotOnMap] = Row(
            english: "Not seen on this map",
            french: "Pas vu sur cette carte",
            italian: "Non presente su questa mappa",
            german: "Auf dieser Karte nicht gesehen",
            spanishSpain: "No visto en este mapa",
            spanishLatam: "No visto en este mapa",
            brPortuguese: "Não visto neste mapa",
            russian: "Не встречается на этой карте",
            ukrainian: "Не трапляється на цій мапі",
            simplifiedChinese: "此地图上未见",
            traditionalChinese: "此地圖上未見",
            japanese: "このマップでは未確認",
            korean: "이 맵에서 보이지 않음",
            polish: "Nie widziano na tej mapie",
            turkish: "Bu haritada görülmedi"
        ),
        [ModTextKey.ControlsToggleTracker] = Row(
            english: "PeakAchiever: show / hide the tracker",
            french: "PeakAchiever\u00A0: afficher / masquer le traqueur",
            italian: "PeakAchiever: mostra / nascondi il tracker",
            german: "PeakAchiever: Tracker ein- / ausblenden",
            spanishSpain: "PeakAchiever: mostrar / ocultar el rastreador",
            spanishLatam: "PeakAchiever: mostrar / ocultar el rastreador",
            brPortuguese: "PeakAchiever: mostrar / ocultar o rastreador",
            russian: "PeakAchiever: показать / скрыть трекер",
            ukrainian: "PeakAchiever: показати / приховати трекер",
            simplifiedChinese: "PeakAchiever：显示 / 隐藏追踪器",
            traditionalChinese: "PeakAchiever：顯示 / 隱藏追蹤器",
            japanese: "PeakAchiever：トラッカーの表示 / 非表示",
            korean: "PeakAchiever: 추적기 표시 / 숨기기",
            polish: "PeakAchiever: pokaż / ukryj tracker",
            turkish: "PeakAchiever: takip panelini göster / gizle"
        ),
        [ModTextKey.SettingsMaxPins] = Row(
            english: "PEAKACHIEVER: MAX PINNED BADGES",
            french: "PEAKACHIEVER\u00A0: DISTINCTIONS ÉPINGLÉES MAX.",
            italian: "PEAKACHIEVER: MAX DISTINTIVI FISSATI",
            german: "PEAKACHIEVER: MAX. ANGEHEFTETE ABZEICHEN",
            spanishSpain: "PEAKACHIEVER: MÁX. INSIGNIAS FIJADAS",
            spanishLatam: "PEAKACHIEVER: MÁX. INSIGNIAS FIJADAS",
            brPortuguese: "PEAKACHIEVER: MÁX. DE INSÍGNIAS FIXADAS",
            russian: "PEAKACHIEVER: МАКС. ЗАКРЕПЛЁННЫХ ЗНАЧКОВ",
            ukrainian: "PEAKACHIEVER: МАКС. ЗАКРІПЛЕНИХ ЗНАЧКІВ",
            simplifiedChinese: "PEAKACHIEVER：固定奖章上限",
            traditionalChinese: "PEAKACHIEVER：釘選徽章上限",
            japanese: "PEAKACHIEVER：ピン留めバッジの上限",
            korean: "PEAKACHIEVER: 고정 배지 최대 수",
            polish: "PEAKACHIEVER: MAKS. PRZYPIĘTYCH ODZNAK",
            turkish: "PEAKACHIEVER: MAKS. SABİTLENEN ROZET"
        ),
        [ModTextKey.SettingsMaxTeamPins] = Row(
            english: "PEAKACHIEVER: MAX TEAM PINS",
            french: "PEAKACHIEVER\u00A0: ÉPINGLES SCOUTS MAX.",
            italian: "PEAKACHIEVER: MAX FISSATI PER GLI SCOUT",
            german: "PEAKACHIEVER: MAX. FÜR PFADFINDER ANGEHEFTET",
            spanishSpain: "PEAKACHIEVER: MÁX. FIJADAS PARA EXPLORADORES",
            spanishLatam: "PEAKACHIEVER: MÁX. FIJADAS PARA EXPLORADORES",
            brPortuguese: "PEAKACHIEVER: MÁX. FIXADAS PARA ESCOTEIROS",
            russian: "PEAKACHIEVER: МАКС. ЗАКРЕПЛЕНИЙ ДЛЯ СКАУТОВ",
            ukrainian: "PEAKACHIEVER: МАКС. ЗАКРІПЛЕНЬ ДЛЯ СКАУТІВ",
            simplifiedChinese: "PEAKACHIEVER：童子军固定上限",
            traditionalChinese: "PEAKACHIEVER：童軍釘選上限",
            japanese: "PEAKACHIEVER：スカウト用ピン留めの上限",
            korean: "PEAKACHIEVER: 스카우트 고정 최대 수",
            polish: "PEAKACHIEVER: MAKS. PRZYPIĘĆ DLA HARCERZY",
            turkish: "PEAKACHIEVER: MAKS. İZCİ SABİTLEMESİ"
        ),
        [ModTextKey.ControlsKeySet] = Row(
            english: "Tracker key set to {0}.",
            french: "Touche du traqueur\u00A0: {0}.",
            italian: "Tasto del tracker: {0}.",
            german: "Tracker-Taste: {0}.",
            spanishSpain: "Tecla del rastreador: {0}.",
            spanishLatam: "Tecla del rastreador: {0}.",
            brPortuguese: "Tecla do rastreador: {0}.",
            russian: "Клавиша трекера: {0}.",
            ukrainian: "Клавіша трекера: {0}.",
            simplifiedChinese: "追踪器按键：{0}。",
            traditionalChinese: "追蹤器按鍵：{0}。",
            japanese: "トラッカーのキー：{0}",
            korean: "추적기 키: {0}",
            polish: "Klawisz trackera: {0}.",
            turkish: "Takip paneli tuşu: {0}."
        ),
        [ModTextKey.TeamButton] = Row(
            english: "Scouts",
            french: "Scouts",
            italian: "Scout",
            german: "Pfadfinder",
            spanishSpain: "Exploradores",
            spanishLatam: "Exploradores",
            brPortuguese: "Escoteiros",
            russian: "Скауты",
            ukrainian: "Скаути",
            simplifiedChinese: "童子军",
            traditionalChinese: "童軍",
            japanese: "スカウト",
            korean: "스카우트",
            polish: "Harcerze",
            turkish: "İzciler"
        ),
        [ModTextKey.TeamTitle] = Row(
            english: "SCOUTS",
            french: "SCOUTS",
            italian: "SCOUT",
            german: "PFADFINDER",
            spanishSpain: "EXPLORADORES",
            spanishLatam: "EXPLORADORES",
            brPortuguese: "ESCOTEIROS",
            russian: "СКАУТЫ",
            ukrainian: "СКАУТИ",
            simplifiedChinese: "童子军",
            traditionalChinese: "童軍",
            japanese: "スカウト",
            korean: "스카우트",
            polish: "HARCERZE",
            turkish: "İZCİLER"
        ),
        [ModTextKey.TeamSummary] = Row(
            english: "{0} scouts in the game · {1} / {2} pinned for the team",
            french: "{0} scouts dans la partie · {1} / {2} épinglées pour l'équipe",
            italian: "{0} scout nella partita · {1} / {2} fissati per la squadra",
            german: "{0} Pfadfinder im Spiel · {1} / {2} fürs Team angeheftet",
            spanishSpain: "{0} exploradores en la partida · {1} / {2} fijadas para el equipo",
            spanishLatam: "{0} exploradores en la partida · {1} / {2} fijadas para el equipo",
            brPortuguese: "{0} escoteiros na partida · {1} / {2} fixadas para a equipe",
            russian: "Скаутов в игре: {0} · закреплено для команды: {1} / {2}",
            ukrainian: "Скаутів у грі: {0} · закріплено для команди: {1} / {2}",
            simplifiedChinese: "游戏中有 {0} 名童子军 · 已为队伍固定 {1} / {2}",
            traditionalChinese: "遊戲中有 {0} 名童軍 · 已為隊伍釘選 {1} / {2}",
            japanese: "ゲーム内のスカウト：{0}人 · チーム用ピン留め：{1} / {2}",
            korean: "게임 내 스카우트 {0}명 · 팀 고정 {1} / {2}",
            polish: "Harcerze w grze: {0} · przypięte dla drużyny: {1} / {2}",
            turkish: "Oyunda {0} izci · takım için sabitlenen: {1} / {2}"
        ),
        [ModTextKey.TeamGroupNobody] = Row(
            english: "Nobody has it",
            french: "Personne ne l'a",
            italian: "Nessuno ce l'ha",
            german: "Niemand hat es",
            spanishSpain: "Nadie la tiene",
            spanishLatam: "Nadie la tiene",
            brPortuguese: "Ninguém tem",
            russian: "Ни у кого нет",
            ukrainian: "Ні в кого немає",
            simplifiedChinese: "无人拥有",
            traditionalChinese: "無人擁有",
            japanese: "誰も持っていない",
            korean: "아무도 없음",
            polish: "Nikt jej nie ma",
            turkish: "Kimsede yok"
        ),
        [ModTextKey.TeamGroupSome] = Row(
            english: "Already earned by some",
            french: "Déjà obtenues par certains",
            italian: "Già ottenuti da alcuni",
            german: "Schon von einigen verdient",
            spanishSpain: "Ya conseguidas por algunos",
            spanishLatam: "Ya obtenidas por algunos",
            brPortuguese: "Já obtidas por alguns",
            russian: "Уже есть у некоторых",
            ukrainian: "Уже є в деяких",
            simplifiedChinese: "部分人已获得",
            traditionalChinese: "部分人已獲得",
            japanese: "一部が獲得済み",
            korean: "일부가 이미 획득",
            polish: "Niektórzy już mają",
            turkish: "Bazılarında zaten var"
        ),
        [ModTextKey.TeamRecommended] = Row(
            english: "Recommended",
            french: "Recommandée",
            italian: "Consigliato",
            german: "Empfohlen",
            spanishSpain: "Recomendada",
            spanishLatam: "Recomendada",
            brPortuguese: "Recomendada",
            russian: "Рекомендуем",
            ukrainian: "Рекомендовано",
            simplifiedChinese: "推荐",
            traditionalChinese: "推薦",
            japanese: "おすすめ",
            korean: "추천",
            polish: "Polecana",
            turkish: "Önerilen"
        ),
        [ModTextKey.TeamHaveIt] = Row(
            english: "{0} / {1} have it",
            french: "{0} / {1} l'ont",
            italian: "{0} / {1} ce l'hanno",
            german: "{0} / {1} haben es",
            spanishSpain: "{0} / {1} la tienen",
            spanishLatam: "{0} / {1} la tienen",
            brPortuguese: "{0} / {1} têm",
            russian: "Есть у {0} / {1}",
            ukrainian: "Є в {0} / {1}",
            simplifiedChinese: "{0} / {1} 人拥有",
            traditionalChinese: "{0} / {1} 人擁有",
            japanese: "{0} / {1}人が所持",
            korean: "{0} / {1}명 보유",
            polish: "Ma ją {0} / {1}",
            turkish: "{0} / {1} kişide var"
        ),
        [ModTextKey.TeamMissingFor] = Row(
            english: "Missing for {0}",
            french: "Il manque à {0}",
            italian: "Manca a {0}",
            german: "Fehlt bei {0}",
            spanishSpain: "Falta: {0}",
            spanishLatam: "Falta: {0}",
            brPortuguese: "Falta para {0}",
            russian: "Нет у: {0}",
            ukrainian: "Немає в: {0}",
            simplifiedChinese: "缺少者：{0}",
            traditionalChinese: "尚缺：{0}",
            japanese: "未所持：{0}",
            korean: "미보유: {0}",
            polish: "Brakuje: {0}",
            turkish: "Eksik olanlar: {0}"
        ),
        [ModTextKey.TeamWithoutTheMod] = Row(
            english: "Without the mod: {0}. Their badges are unknown, and they will not see the team pins.",
            french: "Sans le mod\u00A0: {0}. Leurs distinctions sont inconnues, et ils ne verront pas les épingles Scouts.",
            italian: "Senza la mod: {0}. I loro distintivi sono sconosciuti e non vedranno i distintivi fissati per la squadra.",
            german: "Ohne den Mod: {0}. Ihre Abzeichen sind unbekannt, und sie sehen die fürs Team angehefteten nicht.",
            spanishSpain: "Sin el mod: {0}. Sus insignias son desconocidas y no verán las fijadas para el equipo.",
            spanishLatam: "Sin el mod: {0}. Sus insignias son desconocidas y no verán las fijadas para el equipo.",
            brPortuguese: "Sem o mod: {0}. As insígnias deles são desconhecidas, e eles não verão as fixadas para a equipe.",
            russian: "Без мода: {0}. Их значки неизвестны, и они не увидят закреплённые для команды.",
            ukrainian: "Без мода: {0}. Їхні значки невідомі, і вони не бачитимуть закріплених для команди.",
            simplifiedChinese: "未安装模组：{0}。无法得知其奖章，且他们看不到为队伍固定的奖章。",
            traditionalChinese: "未安裝模組：{0}。無法得知其徽章，且他們看不到為隊伍釘選的徽章。",
            japanese: "Modなし：{0}。バッジは不明で、チーム用のピン留めも表示されません。",
            korean: "모드 미설치: {0}. 이들의 배지는 알 수 없으며, 팀 고정도 보이지 않습니다.",
            polish: "Bez moda: {0}. Ich odznaki są nieznane i nie zobaczą przypiętych dla drużyny.",
            turkish: "Modu olmayanlar: {0}. Rozetleri bilinmiyor ve takım sabitlemelerini görmeyecekler."
        ),
        [ModTextKey.RefusalTeamFull] = Row(
            english: "{0} team pins at most. Unpin one, or raise the limit in Settings, General.",
            french: "{0} épingles Scouts au maximum. Retirez-en une, ou augmentez la limite dans Paramètres, Général.",
            italian: "Al massimo {0} distintivi fissati per la squadra. Rimuovine uno o alza il limite in Impostazioni, Generali.",
            german: "Höchstens {0} fürs Team angeheftete Abzeichen. Löse eines oder erhöhe das Limit unter Einstellungen, Allgemein.",
            spanishSpain: "Máximo de {0} insignias fijadas para el equipo. Quita una o sube el límite en Ajustes, General.",
            spanishLatam: "Máximo de {0} insignias fijadas para el equipo. Quita una o aumenta el límite en Ajustes, General.",
            brPortuguese: "No máximo {0} insígnias fixadas para a equipe. Remova uma ou aumente o limite em Configurações, Geral.",
            russian: "Для команды можно закрепить не больше {0} значков. Уберите один или увеличьте лимит в разделе Настройки, Общие.",
            ukrainian: "Для команди можна закріпити не більше {0} значків. Приберіть один або збільште ліміт у розділі Налаштування, Загальні параметри.",
            simplifiedChinese: "最多为队伍固定 {0} 枚奖章。请取消固定一枚，或在“设置”的“通用”中提高上限。",
            traditionalChinese: "最多為隊伍釘選 {0} 枚徽章。請取消釘選一枚，或在「設定」的「一般」中提高上限。",
            japanese: "チーム用にピン留めできるバッジは最大{0}個です。1つ外すか、「設定」の「全般」で上限を上げてください。",
            korean: "팀용 배지는 최대 {0}개까지 고정할 수 있습니다. 하나를 해제하거나 설정의 일반에서 한도를 높이세요.",
            polish: "Limit odznak przypiętych dla drużyny: {0}. Odepnij jedną lub zwiększ limit w: Ustawienia, Ogólne.",
            turkish: "Takım için en fazla {0} rozet sabitlenebilir. Birini kaldır ya da Ayarlar, Genel bölümünden sınırı artır."
        ),
        [ModTextKey.StatsButton] = Row(
            english: "Statistics",
            french: "Statistiques",
            italian: "Statistiche",
            german: "Statistiken",
            spanishSpain: "Estadísticas",
            spanishLatam: "Estadísticas",
            brPortuguese: "Estatísticas",
            russian: "Статистика",
            ukrainian: "Статистика",
            simplifiedChinese: "统计",
            traditionalChinese: "統計",
            japanese: "統計",
            korean: "통계",
            polish: "Statystyki",
            turkish: "İstatistikler"
        ),
        [ModTextKey.StatsTitle] = Row(
            english: "STATISTICS",
            french: "STATISTIQUES",
            italian: "STATISTICHE",
            german: "STATISTIKEN",
            spanishSpain: "ESTADÍSTICAS",
            spanishLatam: "ESTADÍSTICAS",
            brPortuguese: "ESTATÍSTICAS",
            russian: "СТАТИСТИКА",
            ukrainian: "СТАТИСТИКА",
            simplifiedChinese: "统计",
            traditionalChinese: "統計",
            japanese: "統計",
            korean: "통계",
            polish: "STATYSTYKI",
            turkish: "İSTATİSTİKLER"
        ),
        [ModTextKey.StatsAscentFallback] = Row(
            english: "Ascent {0}",
            french: "Ascension {0}",
            italian: "Scalata {0}",
            german: "Aufstieg {0}",
            spanishSpain: "Ascenso {0}",
            spanishLatam: "Ascenso {0}",
            brPortuguese: "Ascensão {0}",
            russian: "Восхождение {0}",
            ukrainian: "Сходження {0}",
            simplifiedChinese: "天阶 {0}",
            traditionalChinese: "高度 {0}",
            japanese: "アセント{0}",
            korean: "오르막 {0}",
            polish: "Podejście {0}",
            turkish: "Yükseliş {0}"
        ),
        [ModTextKey.StatsColumnBiome] = Row(
            english: "Biome",
            french: "Biome",
            italian: "Bioma",
            german: "Biom",
            spanishSpain: "Bioma",
            spanishLatam: "Bioma",
            brPortuguese: "Bioma",
            russian: "Биом",
            ukrainian: "Біом",
            simplifiedChinese: "地形",
            traditionalChinese: "生態系",
            japanese: "バイオーム",
            korean: "구역",
            polish: "Biom",
            turkish: "Biyom"
        ),
        [ModTextKey.StatsColumnTimes] = Row(
            english: "Times",
            french: "Fois",
            italian: "Volte",
            german: "Anzahl",
            spanishSpain: "Veces",
            spanishLatam: "Veces",
            brPortuguese: "Vezes",
            russian: "Раз",
            ukrainian: "Разів",
            simplifiedChinese: "次数",
            traditionalChinese: "次數",
            japanese: "回数",
            korean: "횟수",
            polish: "Razy",
            turkish: "Kez"
        ),
        [ModTextKey.StatsColumnMedian] = Row(
            english: "Median",
            french: "Médiane",
            italian: "Mediana",
            german: "Median",
            spanishSpain: "Mediana",
            spanishLatam: "Mediana",
            brPortuguese: "Mediana",
            russian: "Медиана",
            ukrainian: "Медіана",
            simplifiedChinese: "中位数",
            traditionalChinese: "中位數",
            japanese: "中央値",
            korean: "중앙값",
            polish: "Mediana",
            turkish: "Medyan"
        ),
        [ModTextKey.StatsColumnBest] = Row(
            english: "Best",
            french: "Meilleur",
            italian: "Migliore",
            german: "Bestzeit",
            spanishSpain: "Mejor",
            spanishLatam: "Mejor",
            brPortuguese: "Melhor",
            russian: "Лучшее",
            ukrainian: "Найкраще",
            simplifiedChinese: "最佳",
            traditionalChinese: "最佳",
            japanese: "ベスト",
            korean: "최고",
            polish: "Najlepszy",
            turkish: "En iyi"
        ),
        [ModTextKey.StatsLayoutTotal] = Row(
            english: "Total ({0})",
            french: "Total ({0})",
            italian: "Totale ({0})",
            german: "Gesamt ({0})",
            spanishSpain: "Total ({0})",
            spanishLatam: "Total ({0})",
            brPortuguese: "Total ({0})",
            russian: "Итого ({0})",
            ukrainian: "Разом ({0})",
            simplifiedChinese: "合计（{0}）",
            traditionalChinese: "合計 ({0})",
            japanese: "合計（{0}）",
            korean: "합계 ({0})",
            polish: "Łącznie ({0})",
            turkish: "Toplam ({0})"
        ),
        [ModTextKey.StatsEmpty] = Row(
            english: "No biome finished at this ascent yet.",
            french: "Aucun biome terminé à cette ascension pour l'instant.",
            italian: "Ancora nessun bioma completato a questa scalata.",
            german: "Noch kein Biom auf diesem Aufstieg abgeschlossen.",
            spanishSpain: "Aún no has terminado ningún bioma en este ascenso.",
            spanishLatam: "Aún no terminaste ningún bioma en este ascenso.",
            brPortuguese: "Nenhum bioma concluído nesta ascensão ainda.",
            russian: "На этом восхождении ещё не пройдено ни одного биома.",
            ukrainian: "На цьому сходженні ще не пройдено жодного біому.",
            simplifiedChinese: "此天阶尚未完成任何地形。",
            traditionalChinese: "此高度尚未完成任何生態系。",
            japanese: "このアセントで完了したバイオームはまだありません。",
            korean: "이 오르막에서 아직 완료한 구역이 없습니다.",
            polish: "Na tym podejściu nie ukończono jeszcze żadnego biomu.",
            turkish: "Bu yükselişte henüz tamamlanan biyom yok."
        ),
        [ModTextKey.StatsNoLowerAscent] = Row(
            english: "No lower ascent has biome times yet: finish a biome at another ascent to see it here.",
            french: "Aucune ascension plus basse n'a encore de temps\u00A0: terminez un biome à une autre ascension pour la voir ici.",
            italian: "Nessuna scalata inferiore ha ancora tempi dei biomi: completa un bioma a un'altra scalata per vederla qui.",
            german: "Noch kein niedrigerer Aufstieg hat Biomzeiten: Schließe ein Biom auf einem anderen Aufstieg ab, um ihn hier zu sehen.",
            spanishSpain: "Ningún ascenso inferior tiene aún tiempos de bioma: termina un bioma en otro ascenso para verlo aquí.",
            spanishLatam: "Ningún ascenso inferior tiene aún tiempos de bioma: termina un bioma en otro ascenso para verlo aquí.",
            brPortuguese: "Nenhuma ascensão inferior tem tempos de bioma ainda: conclua um bioma em outra ascensão para vê-la aqui.",
            russian: "У восхождений ниже ещё нет времени биомов: пройдите биом на другом восхождении, чтобы увидеть его здесь.",
            ukrainian: "Нижчі сходження ще не мають часу біомів: пройдіть біом на іншому сходженні, щоб побачити його тут.",
            simplifiedChinese: "更低的天阶尚无地形用时：在其他天阶完成一个地形即可在此查看。",
            traditionalChinese: "更低的高度尚無生態系時間：在其他高度完成一個生態系即可在此查看。",
            japanese: "これより低いアセントにはまだバイオームのタイムがありません。別のアセントでバイオームを完了するとここに表示されます。",
            korean: "더 낮은 오르막에는 아직 구역 기록이 없습니다. 다른 오르막에서 구역을 완료하면 여기에 표시됩니다.",
            polish: "Żadne niższe podejście nie ma jeszcze czasów biomów: ukończ biom na innym podejściu, by je tu zobaczyć.",
            turkish: "Daha düşük bir yükselişte henüz biyom süresi yok: burada görmek için başka bir yükselişte bir biyom tamamla."
        ),
        [ModTextKey.StatsNoHigherAscent] = Row(
            english: "No higher ascent has biome times yet: finish a biome at another ascent to see it here.",
            french: "Aucune ascension plus haute n'a encore de temps\u00A0: terminez un biome à une autre ascension pour la voir ici.",
            italian: "Nessuna scalata superiore ha ancora tempi dei biomi: completa un bioma a un'altra scalata per vederla qui.",
            german: "Noch kein höherer Aufstieg hat Biomzeiten: Schließe ein Biom auf einem anderen Aufstieg ab, um ihn hier zu sehen.",
            spanishSpain: "Ningún ascenso superior tiene aún tiempos de bioma: termina un bioma en otro ascenso para verlo aquí.",
            spanishLatam: "Ningún ascenso superior tiene aún tiempos de bioma: termina un bioma en otro ascenso para verlo aquí.",
            brPortuguese: "Nenhuma ascensão superior tem tempos de bioma ainda: conclua um bioma em outra ascensão para vê-la aqui.",
            russian: "У восхождений выше ещё нет времени биомов: пройдите биом на другом восхождении, чтобы увидеть его здесь.",
            ukrainian: "Вищі сходження ще не мають часу біомів: пройдіть біом на іншому сходженні, щоб побачити його тут.",
            simplifiedChinese: "更高的天阶尚无地形用时：在其他天阶完成一个地形即可在此查看。",
            traditionalChinese: "更高的高度尚無生態系時間：在其他高度完成一個生態系即可在此查看。",
            japanese: "これより高いアセントにはまだバイオームのタイムがありません。別のアセントでバイオームを完了するとここに表示されます。",
            korean: "더 높은 오르막에는 아직 구역 기록이 없습니다. 다른 오르막에서 구역을 완료하면 여기에 표시됩니다.",
            polish: "Żadne wyższe podejście nie ma jeszcze czasów biomów: ukończ biom na innym podejściu, by je tu zobaczyć.",
            turkish: "Daha yüksek bir yükselişte henüz biyom süresi yok: burada görmek için başka bir yükselişte bir biyom tamamla."
        ),
        [ModTextKey.StatsErase] = Row(
            english: "Erase this ascent",
            french: "Effacer cette ascension",
            italian: "Cancella questa scalata",
            german: "Diesen Aufstieg löschen",
            spanishSpain: "Borrar este ascenso",
            spanishLatam: "Borrar este ascenso",
            brPortuguese: "Apagar esta ascensão",
            russian: "Стереть это восхождение",
            ukrainian: "Стерти це сходження",
            simplifiedChinese: "清除此天阶",
            traditionalChinese: "清除此高度",
            japanese: "このアセントを消去",
            korean: "이 오르막 기록 삭제",
            polish: "Usuń to podejście",
            turkish: "Bu yükselişi sil"
        ),
        [ModTextKey.StatsEraseConfirm] = Row(
            english: "Click again to erase {0}",
            french: "Cliquez encore pour effacer {0}",
            italian: "Clicca di nuovo per cancellare {0}",
            german: "Erneut klicken, um {0} zu löschen",
            spanishSpain: "Vuelve a hacer clic para borrar {0}",
            spanishLatam: "Haz clic de nuevo para borrar {0}",
            brPortuguese: "Clique de novo para apagar {0}",
            russian: "Нажмите ещё раз, чтобы стереть: {0}",
            ukrainian: "Натисніть ще раз, щоб стерти: {0}",
            simplifiedChinese: "再次点击以清除{0}",
            traditionalChinese: "再次點擊以清除{0}",
            japanese: "もう一度クリックで{0}を消去",
            korean: "다시 클릭하면 {0} 삭제",
            polish: "Kliknij ponownie, by usunąć: {0}",
            turkish: "Silmek için tekrar tıkla: {0}"
        ),
        [ModTextKey.StatsErased] = Row(
            english: "{0}: biome times erased.",
            french: "{0}\u00A0: temps des biomes effacés.",
            italian: "{0}: tempi dei biomi cancellati.",
            german: "{0}: Biomzeiten gelöscht.",
            spanishSpain: "{0}: tiempos de bioma borrados.",
            spanishLatam: "{0}: tiempos de bioma borrados.",
            brPortuguese: "{0}: tempos de bioma apagados.",
            russian: "{0}: время биомов стёрто.",
            ukrainian: "{0}: час біомів стерто.",
            simplifiedChinese: "{0}：地形用时已清除。",
            traditionalChinese: "{0}：生態系時間已清除。",
            japanese: "{0}：バイオームのタイムを消去しました。",
            korean: "{0}: 구역 기록 삭제됨.",
            polish: "{0}: czasy biomów usunięte.",
            turkish: "{0}: biyom süreleri silindi."
        ),
        [ModTextKey.StatsEraseFailed] = Row(
            english: "Could not erase the file; see LogOutput.log.",
            french: "Impossible d'effacer le fichier\u00A0: voir LogOutput.log.",
            italian: "Impossibile cancellare il file: vedi LogOutput.log.",
            german: "Datei nicht gelöscht: siehe LogOutput.log.",
            spanishSpain: "No se pudo borrar el archivo: consulta LogOutput.log.",
            spanishLatam: "No se pudo borrar el archivo: consulta LogOutput.log.",
            brPortuguese: "Não foi possível apagar o arquivo: veja LogOutput.log.",
            russian: "Не удалось стереть файл: см. LogOutput.log.",
            ukrainian: "Не вдалося стерти файл: див. LogOutput.log.",
            simplifiedChinese: "无法清除文件：请查看 LogOutput.log。",
            traditionalChinese: "無法清除檔案：請查看 LogOutput.log。",
            japanese: "ファイルを消去できませんでした：LogOutput.logを確認してください。",
            korean: "파일을 삭제하지 못했습니다. LogOutput.log를 확인하세요.",
            polish: "Nie udało się usunąć pliku: zob. LogOutput.log.",
            turkish: "Dosya silinemedi: LogOutput.log dosyasına bak."
        ),
        [ModTextKey.StatsClose] = Row(
            english: "Close",
            french: "Fermer",
            italian: "Chiudi",
            german: "Schließen",
            spanishSpain: "Cerrar",
            spanishLatam: "Cerrar",
            brPortuguese: "Fechar",
            russian: "Закрыть",
            ukrainian: "Закрити",
            simplifiedChinese: "关闭",
            traditionalChinese: "關閉",
            japanese: "閉じる",
            korean: "닫기",
            polish: "Zamknij",
            turkish: "Kapat"
        ),
        [ModTextKey.AchievementsDisabled] = Row(
            english: "Achievements are disabled for this run",
            french: "Succès désactivés pour cette run",
            italian: "Obiettivi disattivati in questa spedizione",
            german: "Erfolge in dieser Expedition deaktiviert",
            spanishSpain: "Logros desactivados en esta expedición",
            spanishLatam: "Logros desactivados en esta expedición",
            brPortuguese: "Conquistas desativadas nesta expedição",
            russian: "Достижения отключены в этой экспедиции",
            ukrainian: "Досягнення вимкнено в цій експедиції",
            simplifiedChinese: "本次探险已禁用成就",
            traditionalChinese: "本次探險已停用成就",
            japanese: "今回の探検では実績が無効です",
            korean: "이번 원정에서는 업적이 비활성화됩니다",
            polish: "Osiągnięcia wyłączone w tej wyprawie",
            turkish: "Bu keşif gezisinde başarımlar devre dışı"
        ),
    };

    public static string Get(ModTextKey key) => In(key, LocalizedText.CURRENT_LANGUAGE);

    /// <summary>The string in a given language.</summary>
    public static string In(ModTextKey key, LocalizedText.Language language) => Table[key][(int)language];

    public static string Format(ModTextKey key, params object[] arguments) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, Get(key), arguments);

    // Named arguments, one per LocalizedText.Language member in its order: a language left out does not compile.
    private static string[] Row(
        string english,
        string french,
        string italian,
        string german,
        string spanishSpain,
        string spanishLatam,
        string brPortuguese,
        string russian,
        string ukrainian,
        string simplifiedChinese,
        string traditionalChinese,
        string japanese,
        string korean,
        string polish,
        string turkish
    ) =>
    [
        english,
        french,
        italian,
        german,
        spanishSpain,
        spanishLatam,
        brPortuguese,
        russian,
        ukrainian,
        simplifiedChinese,
        traditionalChinese,
        japanese,
        korean,
        polish,
        turkish,
    ];
}
